title: "Prompting Payers Project"
description: "Documentación completa de IA, Prompting, LLM y RAG"
theme: "just-the-docs"

url: "https://alesfer1981.github.io"
baseurl: "/Prompting_payers_project"

# Activa búsqueda interna
search_enabled: true

# Activa el sidebar automático
nav_sort: case_insensitive
aux_links:
  "Repo en GitHub":
    - "https://github.com/Alesfer1981/Prompting_payers_project"

# Menú jerárquico
just_the_docs:
  collections:
    docs:
      name: Documentación
